### ISSUE TITLE
[Feature Request] Adding a Watch of Flowing Time equivalent item

### ISSUE THREAD

**Issue by CelestialAbyss** [MaxNeedsSnacks/gag#21]
I was wondering if it would be possible I add something similar to the Watch of Flowing Time on a pedestal since I don't want to add ProjectE just for said item.

Your mod is best suited since it already has the Temporal Pouch so it follows a similar theme

**Comment by MaxNeedsSnacks** [comment]
I'm sorry but that's definitely not happening; you can probably use Torcherino or a comparable mod, but the one reason I implemented any tick accelerating in this mod at all is because at least with the Temporal Pouch (or rather, the Time In A Bottle mechanic it's based on), you have to actually expend a resource (that being collected time) to accelerate blocks, and it also only works with active maintenance; those are both conscious design decisions
