### ISSUE TITLE
Version for 1.12.2

### ISSUE THREAD

**Issue by KimberYT** [MaxNeedsSnacks/gag#3]
Just wondering if you would be able to make a version for 1.12.2, solely because so many mod packs are in that version.
The mod seems really good and would love to see it in this version
Have no clue how difficult or anything this is just wanted to know if it is possible

**Comment by MaxNeedsSnacks** [comment]
I'm sorry, but both the toolchain and the Minecraft codebase itself have changed so drastically since 1.12 (including a bump in the Java version, the flattening that happened in 1.13, and a whole bunch of other stuff) that it's just not practical to backport this (especially since a good part of its features already exists in some other form), so I'll only keep developing this for 1.18.2 and beyond

**Comment by ArnauGames** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/random-things
